# Generated by Django 5.1.2 on 2025-01-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testskool', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
